[versions]
kotlin = "2.3.21"
ktlint = "12.1.2"
detekt = "1.23.7"
dokka  = "2.0.0"
kover  = "0.9.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlin-jvm          = { id = "org.jetbrains.kotlin.jvm",           version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktlint              = { id = "org.jlleitschuh.gradle.ktlint",      version.ref = "ktlint"  }
detekt              = { id = "io.gitlab.arturbosch.detekt",        version.ref = "detekt"  }
dokka               = { id = "org.jetbrains.dokka",                version.ref = "dokka"   }
kover               = { id = "org.jetbrains.kotlinx.kover",        version.ref = "kover"   }
